version: '3'
services:
  app:
    build:
      context: node
    container_name: app
    hostname: app
    networks:
      - node-network
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build:
      context: nginx
    container_name: nginx
    hostname: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
    
  db:
    build: ./db
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always #restarta sozinho se o container cair
    tty: true #habilita bash interativo
    volumes:
      - ./mysql:/var/lib/mysql #mapear volume para nao perder dados
    environment:
      - MYSQL_DATABASE=nodedb #cria o bd automaticamente
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

